server:
  port: 8085
camel:
  server-port: 5000
  springboot:
    main-run-controller: true
  dataformat:
    jackson:
      auto-discover-object-mapper: true

zeebe:
  client:
    max-execution-threads: 100
    number-of-workers: 5
    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
  broker:
    contactpoint: "localhost:26500"
  init-transfer:
    wait-timer: 5
  wait-tnm-pay-request-period: 60

management:
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    ROOT: INFO

channel:
  host: "http://localhost:8082"

paybill:
  account-holding-institution-id: "oaf"
  default-ams: "roster"
  default-ams-short-code: "12345678"
  groups:
    - business-short-code: ${ACCOUNTS_FINERACT_PAYBILL_SHORTCODE:24322607}
      ams: "fineract"
      base-url: ${ACCOUNTS_FINERACT_BASEURL:http://127.24.0.7:5000}
      currency: ${ACCOUNTS_FINERACT_CURRENCY:MWK}
    - business-short-code: ${ACCOUNTS_ROSTER_PAYBILL_SHORTCODE:12345678}
      ams: "roster"
      base-url: ${ACCOUNTS_ROSTER_BASEURL:http://localhost:5000}
      currency: ${ACCOUNTS_ROSTER_CURRENCY:MWK}
